<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateDgiUbiCodesTable extends Migration
{
    public function up()
    {
        Schema::create('dgi_ubi_codes', function (Blueprint $table) {
            $table->id();
            $table->string('codigo'); 
            $table->string('nombre');
            $table->string('tipo');
            $table->timestamps();
        });

        // Insert data
        DB::table('dgi_ubi_codes')->insert([
            ['codigo' => '1', 'nombre' => 'BOCAS DEL TORO', 'tipo' => 'provincia'],
            ['codigo' => '1-1', 'nombre' => 'BOCAS DEL TORO', 'tipo' => 'distrito'],
            ['codigo' => '1-1-1', 'nombre' => 'BOCAS DEL TORO (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '1-1-2', 'nombre' => 'BASTIMENTOS', 'tipo' => 'corregimiento'],
            ['codigo' => '1-1-3', 'nombre' => 'CAUCHERO', 'tipo' => 'corregimiento'],
            ['codigo' => '1-1-4', 'nombre' => 'PUNTA LAUREL', 'tipo' => 'corregimiento'],
            ['codigo' => '1-1-5', 'nombre' => 'TIERRA OSCURA', 'tipo' => 'corregimiento'],
            ['codigo' => '1-2', 'nombre' => 'CHANGUINOLA', 'tipo' => 'distrito'],
            ['codigo' => '1-2-1', 'nombre' => 'CHANGUINOLA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '1-2-2', 'nombre' => 'ALMIRANTE', 'tipo' => 'corregimiento'],
            ['codigo' => '1-2-3', 'nombre' => 'GUABITO', 'tipo' => 'corregimiento'],
            ['codigo' => '1-2-4', 'nombre' => 'TERIBE', 'tipo' => 'corregimiento'],
            ['codigo' => '1-2-5', 'nombre' => 'VALLE DEL RISCO', 'tipo' => 'corregimiento'],
            ['codigo' => '1-2-6', 'nombre' => 'EL EMPALME', 'tipo' => 'corregimiento'],
            ['codigo' => '1-2-7', 'nombre' => 'LAS TABLAS', 'tipo' => 'corregimiento'],
            ['codigo' => '1-3', 'nombre' => 'CHIRIQUI GRANDE', 'tipo' => 'distrito'],
            ['codigo' => '1-3-1', 'nombre' => 'CHIRIQUI GRANDE (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '1-3-2', 'nombre' => 'MIRAMAR', 'tipo' => 'corregimiento'],
            ['codigo' => '1-3-3', 'nombre' => 'PUNTA PEÑA', 'tipo' => 'corregimiento'],
            ['codigo' => '1-3-4', 'nombre' => 'PUNTA ROBALO', 'tipo' => 'corregimiento'],
            ['codigo' => '1-3-5', 'nombre' => 'RAMBALA', 'tipo' => 'corregimiento'],
            ['codigo' => '2', 'nombre' => 'COCLE', 'tipo' => 'provincia'],
            ['codigo' => '2-1', 'nombre' => 'AGUADULCE', 'tipo' => 'distrito'],
            ['codigo' => '2-1-1', 'nombre' => 'AGUADULCE (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '2-1-2', 'nombre' => 'EL CRISTO', 'tipo' => 'corregimiento'],
            ['codigo' => '2-1-3', 'nombre' => 'EL ROBLE', 'tipo' => 'corregimiento'],
            ['codigo' => '2-1-4', 'nombre' => 'POCRI', 'tipo' => 'corregimiento'],
            ['codigo' => '2-1-5', 'nombre' => 'BARRIOS UNIDOS', 'tipo' => 'corregimiento'],
            ['codigo' => '2-2', 'nombre' => 'ANTON', 'tipo' => 'distrito'],
            ['codigo' => '2-2-1', 'nombre' => 'ANTON (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '2-2-2', 'nombre' => 'CABUYA', 'tipo' => 'corregimiento'],
            ['codigo' => '2-2-3', 'nombre' => 'EL CHIRU', 'tipo' => 'corregimiento'],
            ['codigo' => '2-2-4', 'nombre' => 'EL RETIRO', 'tipo' => 'corregimiento'],
            ['codigo' => '2-2-5', 'nombre' => 'EL VALLE', 'tipo' => 'corregimiento'],
            ['codigo' => '2-2-6', 'nombre' => 'JUAN DIAZ', 'tipo' => 'corregimiento'],
            ['codigo' => '2-2-7', 'nombre' => 'RIO HATO', 'tipo' => 'corregimiento'],
            ['codigo' => '2-2-8', 'nombre' => 'SAN JUAN DE DIOS', 'tipo' => 'corregimiento'],
            ['codigo' => '2-2-9', 'nombre' => 'SANTA RITA', 'tipo' => 'corregimiento'],
            ['codigo' => '2-2-10', 'nombre' => 'CABALLERO', 'tipo' => 'corregimiento'],
            ['codigo' => '2-3', 'nombre' => 'LA PINTADA', 'tipo' => 'distrito'],
            ['codigo' => '2-3-1', 'nombre' => 'LA PINTADA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '2-3-2', 'nombre' => 'EL HARINO', 'tipo' => 'corregimiento'],
            ['codigo' => '2-3-3', 'nombre' => 'EL POTRERO', 'tipo' => 'corregimiento'],
            ['codigo' => '2-3-4', 'nombre' => 'LLANO GRANDE', 'tipo' => 'corregimiento'],
            ['codigo' => '2-3-5', 'nombre' => 'PIEDRAS GORDAS', 'tipo' => 'corregimiento'],
            ['codigo' => '2-3-6', 'nombre' => 'LAS LOMAS', 'tipo' => 'corregimiento'],
            ['codigo' => '2-4', 'nombre' => 'NATA', 'tipo' => 'distrito'],
            ['codigo' => '2-4-1', 'nombre' => 'NATA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '2-4-2', 'nombre' => 'CAPELLANIA', 'tipo' => 'corregimiento'],
            ['codigo' => '2-4-3', 'nombre' => 'EL CAÑO', 'tipo' => 'corregimiento'],
            ['codigo' => '2-4-4', 'nombre' => 'GUZMAN', 'tipo' => 'corregimiento'],
            ['codigo' => '2-4-5', 'nombre' => 'LAS HUACAS', 'tipo' => 'corregimiento'],
            ['codigo' => '2-4-6', 'nombre' => 'TOZA', 'tipo' => 'corregimiento'],
            ['codigo' => '2-5', 'nombre' => 'OLA', 'tipo' => 'distrito'],
            ['codigo' => '2-5-1', 'nombre' => 'OLA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '2-5-2', 'nombre' => 'EL COPE', 'tipo' => 'corregimiento'],
            ['codigo' => '2-5-3', 'nombre' => 'EL PALMAR', 'tipo' => 'corregimiento'],
            ['codigo' => '2-5-4', 'nombre' => 'EL PICACHO', 'tipo' => 'corregimiento'],
            ['codigo' => '2-5-5', 'nombre' => 'LA PAVA', 'tipo' => 'corregimiento'],
            ['codigo' => '2-6', 'nombre' => 'PENONOME', 'tipo' => 'distrito'],
            ['codigo' => '2-6-1', 'nombre' => 'PENONOME (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '2-6-2', 'nombre' => 'CAÑAVERAL', 'tipo' => 'corregimiento'],
            ['codigo' => '2-6-3', 'nombre' => 'COCLE', 'tipo' => 'corregimiento'],
            ['codigo' => '2-6-4', 'nombre' => 'CHIGUIRI ARRIBA', 'tipo' => 'corregimiento'],
            ['codigo' => '2-6-5', 'nombre' => 'EL COCO', 'tipo' => 'corregimiento'],
            ['codigo' => '2-6-6', 'nombre' => 'PAJONAL', 'tipo' => 'corregimiento'],
            ['codigo' => '2-6-7', 'nombre' => 'RIO GRANDE', 'tipo' => 'corregimiento'],
            ['codigo' => '2-6-8', 'nombre' => 'RIO INDIO', 'tipo' => 'corregimiento'],
            ['codigo' => '2-6-9', 'nombre' => 'TOABRE', 'tipo' => 'corregimiento'],
            ['codigo' => '2-6-10', 'nombre' => 'TULU', 'tipo' => 'corregimiento'],
            ['codigo' => '3', 'nombre' => 'COLON', 'tipo' => 'provincia'],
            ['codigo' => '3-1', 'nombre' => 'COLON', 'tipo' => 'distrito'],
            ['codigo' => '3-1-1', 'nombre' => 'BARRIO NORTE', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-2', 'nombre' => 'BARRIO SUR', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-3', 'nombre' => 'BUENA VISTA', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-4', 'nombre' => 'CATIVA', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-5', 'nombre' => 'CIRICITO', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-6', 'nombre' => 'CRISTOBAL', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-7', 'nombre' => 'ESCOBAL', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-8', 'nombre' => 'LIMON', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-9', 'nombre' => 'NUEVA PROVIDENCIA', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-10', 'nombre' => 'PUERTO PILON', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-11', 'nombre' => 'SABANITAS', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-12', 'nombre' => 'SALAMANCA', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-13', 'nombre' => 'SAN JUAN', 'tipo' => 'corregimiento'],
            ['codigo' => '3-1-14', 'nombre' => 'SANTA ROSA', 'tipo' => 'corregimiento'],
            ['codigo' => '3-2', 'nombre' => 'CHAGRES', 'tipo' => 'distrito'],
            ['codigo' => '3-2-1', 'nombre' => 'NUEVO CHAGRES (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '3-2-2', 'nombre' => 'ACHIOTE', 'tipo' => 'corregimiento'],
            ['codigo' => '3-2-3', 'nombre' => 'EL GUABO', 'tipo' => 'corregimiento'],
            ['codigo' => '3-2-4', 'nombre' => 'LA ENCANTADA', 'tipo' => 'corregimiento'],
            ['codigo' => '3-2-5', 'nombre' => 'PALMAS BELLAS', 'tipo' => 'corregimiento'],
            ['codigo' => '3-2-6', 'nombre' => 'PIÑA', 'tipo' => 'corregimiento'],
            ['codigo' => '3-2-7', 'nombre' => 'SALUD', 'tipo' => 'corregimiento'],
            ['codigo' => '3-3', 'nombre' => 'DONOSO', 'tipo' => 'distrito'],
            ['codigo' => '3-3-1', 'nombre' => 'MIGUEL DE LA BORDA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '3-3-2', 'nombre' => 'COCLE DEL NORTE', 'tipo' => 'corregimiento'],
            ['codigo' => '3-3-3', 'nombre' => 'EL GUASIMO', 'tipo' => 'corregimiento'],
            ['codigo' => '3-3-4', 'nombre' => 'GOBEA', 'tipo' => 'corregimiento'],
            ['codigo' => '3-3-5', 'nombre' => 'RIO INDIO', 'tipo' => 'corregimiento'],
            ['codigo' => '3-3-6', 'nombre' => 'SAN JOSE DEL GENERAL', 'tipo' => 'corregimiento'],
            ['codigo' => '3-4', 'nombre' => 'PORTOBELO', 'tipo' => 'distrito'],
            ['codigo' => '3-4-1', 'nombre' => 'PORTOBELO (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '3-4-2', 'nombre' => 'CACIQUE', 'tipo' => 'corregimiento'],
            ['codigo' => '3-4-3', 'nombre' => 'GARROTE', 'tipo' => 'corregimiento'],
            ['codigo' => '3-4-4', 'nombre' => 'ISLA GRANDE', 'tipo' => 'corregimiento'],
            ['codigo' => '3-4-5', 'nombre' => 'MARIA CHIQUITA', 'tipo' => 'corregimiento'],
            ['codigo' => '3-5', 'nombre' => 'SANTA ISABEL', 'tipo' => 'distrito'],
            ['codigo' => '3-5-1', 'nombre' => 'PALENQUE (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '3-5-2', 'nombre' => 'CUANGO', 'tipo' => 'corregimiento'],
            ['codigo' => '3-5-3', 'nombre' => 'MIRAMAR', 'tipo' => 'corregimiento'],
            ['codigo' => '3-5-4', 'nombre' => 'NOMBRE DE DIOS', 'tipo' => 'corregimiento'],
            ['codigo' => '3-5-5', 'nombre' => 'PALMIRA', 'tipo' => 'corregimiento'],
            ['codigo' => '3-5-6', 'nombre' => 'PLAYA CHIQUITA', 'tipo' => 'corregimiento'],
            ['codigo' => '3-5-7', 'nombre' => 'SANTA ISABEL', 'tipo' => 'corregimiento'],
            ['codigo' => '3-5-8', 'nombre' => 'VIENTO FRIO', 'tipo' => 'corregimiento'],
            ['codigo' => '4', 'nombre' => 'CHIRIQUI', 'tipo' => 'provincia'],
            ['codigo' => '4-1', 'nombre' => 'ALANJE', 'tipo' => 'distrito'],
            ['codigo' => '4-1-1', 'nombre' => 'ALANJE (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-1-2', 'nombre' => 'DIVALA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-1-3', 'nombre' => 'EL TEJAR', 'tipo' => 'corregimiento'],
            ['codigo' => '4-1-4', 'nombre' => 'GUARUMAL', 'tipo' => 'corregimiento'],
            ['codigo' => '4-1-5', 'nombre' => 'PALO GRANDE', 'tipo' => 'corregimiento'],
            ['codigo' => '4-1-6', 'nombre' => 'QUEREVALO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-1-7', 'nombre' => 'SANTO TOMAS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-1-8', 'nombre' => 'CANTA GALLO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-1-9', 'nombre' => 'NUEVO MEXICO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-2', 'nombre' => 'BARU', 'tipo' => 'distrito'],
            ['codigo' => '4-2-1', 'nombre' => 'PUERTO ARMUELLES (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-2-2', 'nombre' => 'LIMONES', 'tipo' => 'corregimiento'],
            ['codigo' => '4-2-3', 'nombre' => 'PROGRESO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-2-4', 'nombre' => 'BACO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-2-5', 'nombre' => 'RODOLFO AGUILAR DELGADO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-3', 'nombre' => 'BOQUERON', 'tipo' => 'distrito'],
            ['codigo' => '4-3-1', 'nombre' => 'BOQUERON (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-3-2', 'nombre' => 'BAGALA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-3-3', 'nombre' => 'CORDILLERA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-3-4', 'nombre' => 'GUABAL', 'tipo' => 'corregimiento'],
            ['codigo' => '4-3-5', 'nombre' => 'GUAYABAL', 'tipo' => 'corregimiento'],
            ['codigo' => '4-3-6', 'nombre' => 'PARAISO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-3-7', 'nombre' => 'PEDREGAL', 'tipo' => 'corregimiento'],
            ['codigo' => '4-3-8', 'nombre' => 'TIJERAS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-4', 'nombre' => 'BOQUETE', 'tipo' => 'distrito'],
            ['codigo' => '4-4-1', 'nombre' => 'BAJO BOQUETE (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-4-2', 'nombre' => 'CALDERA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-4-3', 'nombre' => 'PALMIRA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-4-4', 'nombre' => 'ALTO BOQUETE', 'tipo' => 'corregimiento'],
            ['codigo' => '4-4-5', 'nombre' => 'JARAMILLO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-4-6', 'nombre' => 'LOS NARANJOS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5', 'nombre' => 'BUGABA', 'tipo' => 'distrito'],
            ['codigo' => '4-5-1', 'nombre' => 'LA CONCEPCION (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-2', 'nombre' => 'ASERRIO DE GARICHE', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-3', 'nombre' => 'BUGABA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-4', 'nombre' => 'CERRO PUNTA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-5', 'nombre' => 'GOMEZ', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-6', 'nombre' => 'LA ESTRELLA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-7', 'nombre' => 'SAN ANDRES', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-8', 'nombre' => 'SANTA MARTA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-9', 'nombre' => 'SANTA ROSA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-10', 'nombre' => 'SANTO DOMINGO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-11', 'nombre' => 'SORTOVA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-12', 'nombre' => 'VOLCAN', 'tipo' => 'corregimiento'],
            ['codigo' => '4-5-13', 'nombre' => 'EL BONGO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-6', 'nombre' => 'DAVID', 'tipo' => 'distrito'],
            ['codigo' => '4-6-1', 'nombre' => 'DAVID (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-6-2', 'nombre' => 'BIJAGUAL', 'tipo' => 'corregimiento'],
            ['codigo' => '4-6-3', 'nombre' => 'COCHEA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-6-4', 'nombre' => 'CHIRIQUI', 'tipo' => 'corregimiento'],
            ['codigo' => '4-6-5', 'nombre' => 'GUACA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-6-6', 'nombre' => 'LAS LOMAS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-6-7', 'nombre' => 'PEDREGAL', 'tipo' => 'corregimiento'],
            ['codigo' => '4-6-8', 'nombre' => 'SAN CARLOS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-6-9', 'nombre' => 'SAN PABLO NUEVO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-6-10', 'nombre' => 'SAN PABLO VIEJO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-7', 'nombre' => 'DOLEGA', 'tipo' => 'distrito'],
            ['codigo' => '4-7-1', 'nombre' => 'DOLEGA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-7-2', 'nombre' => 'DOS RIOS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-7-3', 'nombre' => 'LOS ANASTACIOS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-7-4', 'nombre' => 'POTRERILLOS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-7-5', 'nombre' => 'POTRERILLOS ABAJO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-7-6', 'nombre' => 'ROVIRA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-7-7', 'nombre' => 'TINAJAS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-7-8', 'nombre' => 'LOS ALGARRROBOS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-8', 'nombre' => 'GUALACA', 'tipo' => 'distrito'],
            ['codigo' => '4-8-1', 'nombre' => 'GUALACA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-8-2', 'nombre' => 'HORNITO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-8-3', 'nombre' => 'LOS ANGELES', 'tipo' => 'corregimiento'],
            ['codigo' => '4-8-4', 'nombre' => 'PAJA DE SOMBRERO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-8-5', 'nombre' => 'RINCON', 'tipo' => 'corregimiento'],
            ['codigo' => '4-9', 'nombre' => 'REMEDIOS', 'tipo' => 'distrito'],
            ['codigo' => '4-9-1', 'nombre' => 'REMEDIOS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-9-2', 'nombre' => 'EL NANCITO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-9-3', 'nombre' => 'EL PORVENIR', 'tipo' => 'corregimiento'],
            ['codigo' => '4-9-4', 'nombre' => 'EL PUERTO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-9-5', 'nombre' => 'SANTA LUCIA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-10', 'nombre' => 'RENACIMIENTO', 'tipo' => 'distrito'],
            ['codigo' => '4-10-1', 'nombre' => 'RIO SERENO (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-10-2', 'nombre' => 'BREÑON', 'tipo' => 'corregimiento'],
            ['codigo' => '4-10-3', 'nombre' => 'CAÑAS GORDAS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-10-4', 'nombre' => 'MONTE LIRIO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-10-5', 'nombre' => 'PLAZA CAISAN', 'tipo' => 'corregimiento'],
            ['codigo' => '4-10-6', 'nombre' => 'SANTA CRUZ', 'tipo' => 'corregimiento'],
            ['codigo' => '4-10-7', 'nombre' => 'DOMINICAL', 'tipo' => 'corregimiento'],
            ['codigo' => '4-10-8', 'nombre' => 'SANTA CLARA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-11', 'nombre' => 'SAN FELIX', 'tipo' => 'distrito'],
            ['codigo' => '4-11-1', 'nombre' => 'LAS LAJAS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-11-2', 'nombre' => 'JUAY', 'tipo' => 'corregimiento'],
            ['codigo' => '4-11-3', 'nombre' => 'LAJAS ADENTRO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-11-4', 'nombre' => 'SAN FELIX', 'tipo' => 'corregimiento'],
            ['codigo' => '4-11-5', 'nombre' => 'SANTA CRUZ', 'tipo' => 'corregimiento'],
            ['codigo' => '4-12', 'nombre' => 'SAN LORENZO', 'tipo' => 'distrito'],
            ['codigo' => '4-12-1', 'nombre' => 'HORCONCITOS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-12-2', 'nombre' => 'BOCA CHICA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-12-3', 'nombre' => 'BOCA DEL MONTE', 'tipo' => 'corregimiento'],
            ['codigo' => '4-12-4', 'nombre' => 'SAN JUAN', 'tipo' => 'corregimiento'],
            ['codigo' => '4-12-5', 'nombre' => 'SAN LORENZO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-13', 'nombre' => 'TOLE', 'tipo' => 'distrito'],
            ['codigo' => '4-13-1', 'nombre' => 'TOLE (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '4-13-2', 'nombre' => 'BELLA VISTA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-13-3', 'nombre' => 'CERRO VIEJO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-13-4', 'nombre' => 'EL CRISTO', 'tipo' => 'corregimiento'],
            ['codigo' => '4-13-5', 'nombre' => 'JUSTO FIDEL PALACIOS', 'tipo' => 'corregimiento'],
            ['codigo' => '4-13-6', 'nombre' => 'LAJAS DE TOLE', 'tipo' => 'corregimiento'],
            ['codigo' => '4-13-7', 'nombre' => 'POTRERO DE CAÑA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-13-8', 'nombre' => 'QUEBRADA DE PIEDRA', 'tipo' => 'corregimiento'],
            ['codigo' => '4-13-9', 'nombre' => 'VELADERO', 'tipo' => 'corregimiento'],
            ['codigo' => '5', 'nombre' => 'DARIEN', 'tipo' => 'provincia'],
            ['codigo' => '5-1', 'nombre' => 'CHEPIGANA', 'tipo' => 'distrito'],
            ['codigo' => '5-1-1', 'nombre' => 'LA PALMA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-2', 'nombre' => 'CAMOGANTI', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-3', 'nombre' => 'CHEPIGANA', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-4', 'nombre' => 'GARACHINE', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-5', 'nombre' => 'JAQUE', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-6', 'nombre' => 'PUERTO PIÑA', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-7', 'nombre' => 'RIO CONGO', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-8', 'nombre' => 'RIO IGLESIAS', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-9', 'nombre' => 'SAMBU', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-10', 'nombre' => 'SETEGANTI', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-11', 'nombre' => 'TAIMATI', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-12', 'nombre' => 'TUCUTI', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-13', 'nombre' => 'AGUA FRIA', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-14', 'nombre' => 'CUCUNATI', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-15', 'nombre' => 'RIO CONGO ARRIBA', 'tipo' => 'corregimiento'],
            ['codigo' => '5-1-16', 'nombre' => 'SANTA FE', 'tipo' => 'corregimiento'],
            ['codigo' => '5-2', 'nombre' => 'PINOGANA', 'tipo' => 'distrito'],
            ['codigo' => '5-2-1', 'nombre' => 'EL REAL DE SANTA MARIA (CABECE', 'tipo' => 'corregimiento'],
            ['codigo' => '5-2-2', 'nombre' => 'BOCA DE CUPE', 'tipo' => 'corregimiento'],
            ['codigo' => '5-2-3', 'nombre' => 'PAYA', 'tipo' => 'corregimiento'],
            ['codigo' => '5-2-4', 'nombre' => 'PINOGANA', 'tipo' => 'corregimiento'],
            ['codigo' => '5-2-5', 'nombre' => 'PUCURO', 'tipo' => 'corregimiento'],
            ['codigo' => '5-2-6', 'nombre' => 'YAPE', 'tipo' => 'corregimiento'],
            ['codigo' => '5-2-7', 'nombre' => 'YAVIZA', 'tipo' => 'corregimiento'],
            ['codigo' => '5-2-8', 'nombre' => 'METETI', 'tipo' => 'corregimiento'],
            ['codigo' => '5-2-9', 'nombre' => 'COMARCA KUNA DE WARGANDI', 'tipo' => 'corregimiento'],
            ['codigo' => '6', 'nombre' => 'HERRERA', 'tipo' => 'provincia'],
            ['codigo' => '6-1', 'nombre' => 'CHITRE', 'tipo' => 'distrito'],
            ['codigo' => '6-1-1', 'nombre' => 'CHITRE (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '6-1-2', 'nombre' => 'LA ARENA', 'tipo' => 'corregimiento'],
            ['codigo' => '6-1-3', 'nombre' => 'MONAGRILLO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-1-4', 'nombre' => 'LLANO BONITO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-1-5', 'nombre' => 'SAN JUAN BAUTISTA', 'tipo' => 'corregimiento'],
            ['codigo' => '6-2', 'nombre' => 'LAS MINAS', 'tipo' => 'distrito'],
            ['codigo' => '6-2-1', 'nombre' => 'LAS MINAS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '6-2-2', 'nombre' => 'CHEPO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-2-3', 'nombre' => 'CHUMICAL', 'tipo' => 'corregimiento'],
            ['codigo' => '6-2-4', 'nombre' => 'EL TORO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-2-5', 'nombre' => 'LEONES', 'tipo' => 'corregimiento'],
            ['codigo' => '6-2-6', 'nombre' => 'QUEBRADA DEL ROSARIO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-2-7', 'nombre' => 'QUEBRADA EL CIPRIAN', 'tipo' => 'corregimiento'],
            ['codigo' => '6-3', 'nombre' => 'LOS POZOS', 'tipo' => 'distrito'],
            ['codigo' => '6-3-1', 'nombre' => 'LOS POZOS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '6-3-2', 'nombre' => 'CAPURI', 'tipo' => 'corregimiento'],
            ['codigo' => '6-3-3', 'nombre' => 'EL CALABACITO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-3-4', 'nombre' => 'EL CEDRO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-3-5', 'nombre' => 'LA ARENA', 'tipo' => 'corregimiento'],
            ['codigo' => '6-3-6', 'nombre' => 'LA PITALOSA', 'tipo' => 'corregimiento'],
            ['codigo' => '6-3-7', 'nombre' => 'LOS CERRITOS', 'tipo' => 'corregimiento'],
            ['codigo' => '6-3-8', 'nombre' => 'LOS CERROS DE PAJA', 'tipo' => 'corregimiento'],
            ['codigo' => '6-3-9', 'nombre' => 'LAS LLANAS', 'tipo' => 'corregimiento'],
            ['codigo' => '6-4', 'nombre' => 'OCU', 'tipo' => 'distrito'],
            ['codigo' => '6-4-1', 'nombre' => 'OCU (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '6-4-2', 'nombre' => 'CERRO LARGO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-4-3', 'nombre' => 'LOS LLANOS', 'tipo' => 'corregimiento'],
            ['codigo' => '6-4-4', 'nombre' => 'LLANO GRANDE', 'tipo' => 'corregimiento'],
            ['codigo' => '6-4-5', 'nombre' => 'PEÑAS CHATAS', 'tipo' => 'corregimiento'],
            ['codigo' => '6-4-6', 'nombre' => 'EL TIJERA', 'tipo' => 'corregimiento'],
            ['codigo' => '6-4-7', 'nombre' => 'MENCHACA', 'tipo' => 'corregimiento'],
            ['codigo' => '6-5', 'nombre' => 'PARITA', 'tipo' => 'distrito'],
            ['codigo' => '6-5-1', 'nombre' => 'PARITA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '6-5-2', 'nombre' => 'CABUYA', 'tipo' => 'corregimiento'],
            ['codigo' => '6-5-3', 'nombre' => 'LOS CASTILLOS', 'tipo' => 'corregimiento'],
            ['codigo' => '6-5-4', 'nombre' => 'LLANO DE LA CRUZ', 'tipo' => 'corregimiento'],
            ['codigo' => '6-5-5', 'nombre' => 'PARIS', 'tipo' => 'corregimiento'],
            ['codigo' => '6-5-6', 'nombre' => 'PORTOBELILLO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-5-7', 'nombre' => 'POTUGA', 'tipo' => 'corregimiento'],
            ['codigo' => '6-6', 'nombre' => 'PESE', 'tipo' => 'distrito'],
            ['codigo' => '6-6-1', 'nombre' => 'PESE (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '6-6-2', 'nombre' => 'LAS CABRAS', 'tipo' => 'corregimiento'],
            ['codigo' => '6-6-3', 'nombre' => 'EL PAJARO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-6-4', 'nombre' => 'EL BARRERO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-6-5', 'nombre' => 'EL PEDREGOSO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-6-6', 'nombre' => 'EL CIRUELO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-6-7', 'nombre' => 'SABANAGRANDE', 'tipo' => 'corregimiento'],
            ['codigo' => '6-6-8', 'nombre' => 'RINCON HONDO', 'tipo' => 'corregimiento'],
            ['codigo' => '6-7', 'nombre' => 'SANTA MARIA', 'tipo' => 'distrito'],
            ['codigo' => '6-7-1', 'nombre' => 'SANTA MARIA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '6-7-2', 'nombre' => 'CHUPAMPA', 'tipo' => 'corregimiento'],
            ['codigo' => '6-7-3', 'nombre' => 'EL RINCON', 'tipo' => 'corregimiento'],
            ['codigo' => '6-7-4', 'nombre' => 'EL LIMON', 'tipo' => 'corregimiento'],
            ['codigo' => '6-7-5', 'nombre' => 'LOS CANELOS', 'tipo' => 'corregimiento'],
            ['codigo' => '7', 'nombre' => 'LOS SANTOS', 'tipo' => 'provincia'],
            ['codigo' => '7-1', 'nombre' => 'GUARARE', 'tipo' => 'distrito'],
            ['codigo' => '7-1-1', 'nombre' => 'GUARARE (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '7-1-2', 'nombre' => 'EL ESPINAL', 'tipo' => 'corregimiento'],
            ['codigo' => '7-1-3', 'nombre' => 'EL MACANO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-1-4', 'nombre' => 'GUARARE ARRIBA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-1-5', 'nombre' => 'LA ENEA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-1-6', 'nombre' => 'LA PASERA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-1-7', 'nombre' => 'LAS TRANCAS', 'tipo' => 'corregimiento'],
            ['codigo' => '7-1-8', 'nombre' => 'LLANO ABAJO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-1-9', 'nombre' => 'EL HATO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-1-10', 'nombre' => 'PERALES', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2', 'nombre' => 'LAS TABLAS', 'tipo' => 'distrito'],
            ['codigo' => '7-2-1', 'nombre' => 'LAS TABLAS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-2', 'nombre' => 'BAJO CORRAL', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-3', 'nombre' => 'BAYANO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-4', 'nombre' => 'EL CARATE', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-5', 'nombre' => 'EL COCAL', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-6', 'nombre' => 'EL MANANTIAL', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-7', 'nombre' => 'EL MUÑOZ', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-8', 'nombre' => 'EL PEDREGOSO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-9', 'nombre' => 'LA LAJA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-10', 'nombre' => 'LA MIEL', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-11', 'nombre' => 'LA PALMA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-12', 'nombre' => 'LA TIZA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-13', 'nombre' => 'LAS PALMITAS', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-14', 'nombre' => 'LAS TABLAS ABAJO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-15', 'nombre' => 'NUARIO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-16', 'nombre' => 'PALMIRA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-17', 'nombre' => 'PEÑA BLANCA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-18', 'nombre' => 'RIO HONDO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-19', 'nombre' => 'SAN JOSE', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-20', 'nombre' => 'SAN MIGUEL', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-21', 'nombre' => 'SANTO DOMINGO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-22', 'nombre' => 'SESTEADERO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-23', 'nombre' => 'VALLE RICO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-2-24', 'nombre' => 'VALLERIQUITO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3', 'nombre' => 'LOS SANTOS', 'tipo' => 'distrito'],
            ['codigo' => '7-3-1', 'nombre' => 'LA VILLA DE LOS SANTOS (CABECE', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-2', 'nombre' => 'EL GUASIMO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-3', 'nombre' => 'LA COLORADA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-4', 'nombre' => 'LA ESPIGADILLA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-5', 'nombre' => 'LAS CRUCES', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-6', 'nombre' => 'LAS GUABAS', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-7', 'nombre' => 'LOS ANGELES', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-8', 'nombre' => 'LOS OLIVOS', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-9', 'nombre' => 'LLANO LARGO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-10', 'nombre' => 'SABANAGRANDE', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-11', 'nombre' => 'SANTA ANA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-12', 'nombre' => 'TRES QUEBRADAS', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-13', 'nombre' => 'AGUA BUENA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-3-14', 'nombre' => 'VILLA LOURDES', 'tipo' => 'corregimiento'],
            ['codigo' => '7-4', 'nombre' => 'MACARACAS', 'tipo' => 'distrito'],
            ['codigo' => '7-4-1', 'nombre' => 'MACARACAS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '7-4-2', 'nombre' => 'BAHIA HONDA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-4-3', 'nombre' => 'BAJOS DE GUERA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-4-4', 'nombre' => 'COROZAL', 'tipo' => 'corregimiento'],
            ['codigo' => '7-4-5', 'nombre' => 'CHUPA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-4-6', 'nombre' => 'EL CEDRO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-4-7', 'nombre' => 'ESPINO AMARILLO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-4-8', 'nombre' => 'LA MESA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-4-9', 'nombre' => 'LAS PALMAS', 'tipo' => 'corregimiento'],
            ['codigo' => '7-4-10', 'nombre' => 'LLANO DE PIEDRA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-4-11', 'nombre' => 'MOGOLLON', 'tipo' => 'corregimiento'],
            ['codigo' => '7-5', 'nombre' => 'PEDASI', 'tipo' => 'distrito'],
            ['codigo' => '7-5-1', 'nombre' => 'PEDASI (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '7-5-2', 'nombre' => 'LOS ASIENTOS', 'tipo' => 'corregimiento'],
            ['codigo' => '7-5-3', 'nombre' => 'MARIABE', 'tipo' => 'corregimiento'],
            ['codigo' => '7-5-4', 'nombre' => 'PURIO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-5-5', 'nombre' => 'ORIA ARRIBA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-6', 'nombre' => 'POCRI', 'tipo' => 'distrito'],
            ['codigo' => '7-6-1', 'nombre' => 'POCRI', 'tipo' => 'corregimiento'],
            ['codigo' => '7-6-2', 'nombre' => 'EL CAÑAFISTULO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-6-3', 'nombre' => 'LAJAMINA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-6-4', 'nombre' => 'PARAISO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-6-5', 'nombre' => 'PARITILLA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-7', 'nombre' => 'TONOSI', 'tipo' => 'distrito'],
            ['codigo' => '7-7-1', 'nombre' => 'TONOSI (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '7-7-2', 'nombre' => 'ALTOS DE GUERA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-7-3', 'nombre' => 'CAÑAS', 'tipo' => 'corregimiento'],
            ['codigo' => '7-7-4', 'nombre' => 'EL BEBEDERO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-7-5', 'nombre' => 'EL CACAO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-7-6', 'nombre' => 'EL CORTEZO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-7-7', 'nombre' => 'FLORES', 'tipo' => 'corregimiento'],
            ['codigo' => '7-7-8', 'nombre' => 'GUANICO', 'tipo' => 'corregimiento'],
            ['codigo' => '7-7-9', 'nombre' => 'LA TRONOSA', 'tipo' => 'corregimiento'],
            ['codigo' => '7-7-10', 'nombre' => 'CAMBUTAL', 'tipo' => 'corregimiento'],
            ['codigo' => '7-7-11', 'nombre' => 'ISLA DE CAQAS', 'tipo' => 'corregimiento'],
            ['codigo' => '8', 'nombre' => 'PANAMA', 'tipo' => 'provincia'],
            ['codigo' => '8-2', 'nombre' => 'BALBOA', 'tipo' => 'distrito'],
            ['codigo' => '8-2-1', 'nombre' => 'SAN MIGUEL (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '8-2-2', 'nombre' => 'LA ENSENADA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-2-3', 'nombre' => 'LA ESMERALDA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-2-4', 'nombre' => 'LA GUINEA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-2-5', 'nombre' => 'PEDRO GONZALEZ', 'tipo' => 'corregimiento'],
            ['codigo' => '8-2-6', 'nombre' => 'SABOGA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-5', 'nombre' => 'CHEPO', 'tipo' => 'distrito'],
            ['codigo' => '8-5-1', 'nombre' => 'CHEPO (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '8-5-2', 'nombre' => 'CAÑITA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-5-3', 'nombre' => 'CHEPILLO', 'tipo' => 'corregimiento'],
            ['codigo' => '8-5-4', 'nombre' => 'EL LLANO', 'tipo' => 'corregimiento'],
            ['codigo' => '8-5-5', 'nombre' => 'LAS MARGARITAS', 'tipo' => 'corregimiento'],
            ['codigo' => '8-5-6', 'nombre' => 'SANTA CRUZ DE CHININA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-5-7', 'nombre' => 'COMARCA KUNA DE MADUNGANDI', 'tipo' => 'corregimiento'],
            ['codigo' => '8-5-8', 'nombre' => 'TORTI', 'tipo' => 'corregimiento'],
            ['codigo' => '8-6', 'nombre' => 'CHIMAN', 'tipo' => 'distrito'],
            ['codigo' => '8-6-1', 'nombre' => 'CHIMAN (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '8-6-2', 'nombre' => 'BRUJAS', 'tipo' => 'corregimiento'],
            ['codigo' => '8-6-3', 'nombre' => 'GONZALO VASQUEZ', 'tipo' => 'corregimiento'],
            ['codigo' => '8-6-4', 'nombre' => 'PASIGA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-6-5', 'nombre' => 'UNION SANTEÑA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8', 'nombre' => 'PANAMA', 'tipo' => 'distrito'],
            ['codigo' => '8-8-1', 'nombre' => 'SAN FELIPE', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-2', 'nombre' => 'EL CHORRILLO', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-3', 'nombre' => 'SANTA ANA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-4', 'nombre' => 'LA EXPOSICION O CALIDONIA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-5', 'nombre' => 'CURUNDU', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-6', 'nombre' => 'BETANIA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-7', 'nombre' => 'BELLA VISTA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-8', 'nombre' => 'PUEBLO NUEVO', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-9', 'nombre' => 'SAN FRANCISCO', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-10', 'nombre' => 'PARQUE LEFEVRE', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-11', 'nombre' => 'RIO ABAJO', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-12', 'nombre' => 'JUAN DIAZ', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-13', 'nombre' => 'PEDREGAL', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-14', 'nombre' => 'ANCON', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-15', 'nombre' => 'CHILIBRE', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-16', 'nombre' => 'LAS CUMBRES', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-17', 'nombre' => 'PACORA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-18', 'nombre' => 'SAN MARTIN', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-19', 'nombre' => 'TOCUMEN', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-20', 'nombre' => 'LAS MAQANITAS', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-21', 'nombre' => '24 DE DICIEMBRE', 'tipo' => 'corregimiento'],
            ['codigo' => '8-8-22', 'nombre' => 'ERNESTO CORDOBA CAMPOS', 'tipo' => 'corregimiento'],
            ['codigo' => '', 'nombre' => 'PANAMA', 'tipo' => 'provincia'],
            ['codigo' => '-', 'nombre' => 'PANAMA', 'tipo' => 'distrito'],
            ['codigo' => '--', 'nombre' => 'ALCALDE DIAZ', 'tipo' => 'corregimiento'],
            ['codigo' => '--', 'nombre' => 'CAIMITILLO', 'tipo' => 'corregimiento'],
            ['codigo' => '--', 'nombre' => 'DON BOSCO', 'tipo' => 'corregimiento'],
            ['codigo' => '--', 'nombre' => 'LAS GARZAS', 'tipo' => 'corregimiento'],
            ['codigo' => '8-10', 'nombre' => 'SAN MIGUELITO', 'tipo' => 'distrito'],
            ['codigo' => '8-10-1', 'nombre' => 'AMELIA DENIS DE ICAZA', 'tipo' => 'corregimiento'],
            ['codigo' => '8-10-2', 'nombre' => 'BELISARIO PORRAS', 'tipo' => 'corregimiento'],
            ['codigo' => '8-10-3', 'nombre' => 'JOSE DOMINGO ESPINAR', 'tipo' => 'corregimiento'],
            ['codigo' => '8-10-4', 'nombre' => 'MATEO ITURRALDE', 'tipo' => 'corregimiento'],
            ['codigo' => '8-10-5', 'nombre' => 'VICTORIANO LORENZO', 'tipo' => 'corregimiento'],
            ['codigo' => '8-10-6', 'nombre' => 'ARNULFO ARIAS', 'tipo' => 'corregimiento'],
            ['codigo' => '8-10-7', 'nombre' => 'BELISARIO FRIAS', 'tipo' => 'corregimiento'],
            ['codigo' => '8-10-8', 'nombre' => 'OMAR TORRIJOS', 'tipo' => 'corregimiento'],
            ['codigo' => '8-10-9', 'nombre' => 'RUFINA ALFARO', 'tipo' => 'corregimiento'],
            ['codigo' => '8-11', 'nombre' => 'TABOGA', 'tipo' => 'distrito'],
            ['codigo' => '8-11-1', 'nombre' => 'TABOGA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '8-11-2', 'nombre' => 'OTOQUE ORIENTE', 'tipo' => 'corregimiento'],
            ['codigo' => '8-11-3', 'nombre' => 'OTOQUE OCCIDENTE', 'tipo' => 'corregimiento'],
            ['codigo' => '9', 'nombre' => 'VERAGUAS', 'tipo' => 'provincia'],
            ['codigo' => '9-1', 'nombre' => 'ATALAYA', 'tipo' => 'distrito'],
            ['codigo' => '9-1-1', 'nombre' => 'ATALAYA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-1-2', 'nombre' => 'EL BARRITO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-1-3', 'nombre' => 'LA MONTAÑUELA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-1-4', 'nombre' => 'LA CARRILLO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-1-5', 'nombre' => 'SAN ANTONIO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2', 'nombre' => 'CALOBRE', 'tipo' => 'distrito'],
            ['codigo' => '9-2-1', 'nombre' => 'CALOBRE (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2-2', 'nombre' => 'BARNIZAL', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2-3', 'nombre' => 'CHITRA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2-4', 'nombre' => 'EL COCLA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2-5', 'nombre' => 'EL POTRERO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2-6', 'nombre' => 'LA LAGUNA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2-7', 'nombre' => 'LA RAYA DE CALOBRE', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2-8', 'nombre' => 'LA TETILLA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2-9', 'nombre' => 'LA YEGUADA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2-10', 'nombre' => 'LAS GUIAS', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2-11', 'nombre' => 'MONJARAS', 'tipo' => 'corregimiento'],
            ['codigo' => '9-2-12', 'nombre' => 'SAN JOSE', 'tipo' => 'corregimiento'],
            ['codigo' => '9-3', 'nombre' => 'CAÑAZAS', 'tipo' => 'distrito'],
            ['codigo' => '9-3-1', 'nombre' => 'CAÑAZAS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-3-2', 'nombre' => 'CERRO PLATA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-3-3', 'nombre' => 'EL PICADOR', 'tipo' => 'corregimiento'],
            ['codigo' => '9-3-4', 'nombre' => 'LOS VALLES', 'tipo' => 'corregimiento'],
            ['codigo' => '9-3-5', 'nombre' => 'SAN JOSE', 'tipo' => 'corregimiento'],
            ['codigo' => '9-3-6', 'nombre' => 'SAN MARCELO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-3-7', 'nombre' => 'EL AROMILLO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-4', 'nombre' => 'LA MEZA', 'tipo' => 'distrito'],
            ['codigo' => '9-4-1', 'nombre' => 'LA MESA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-4-2', 'nombre' => 'BISVALLES', 'tipo' => 'corregimiento'],
            ['codigo' => '9-4-3', 'nombre' => 'BORO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-4-4', 'nombre' => 'LLANO GRANDE', 'tipo' => 'corregimiento'],
            ['codigo' => '9-4-5', 'nombre' => 'SAN BARTOLO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-4-6', 'nombre' => 'LOS MILAGROS', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5', 'nombre' => 'LAS PALMAS', 'tipo' => 'distrito'],
            ['codigo' => '9-5-1', 'nombre' => 'LAS PALMAS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5-2', 'nombre' => 'CERRO DE CASA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5-3', 'nombre' => 'COROZAL', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5-4', 'nombre' => 'EL MARIA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5-5', 'nombre' => 'EL PRADO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5-6', 'nombre' => 'EL RINCON', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5-7', 'nombre' => 'LOLA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5-8', 'nombre' => 'PIXVAE', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5-9', 'nombre' => 'PUERTO VIDAL', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5-10', 'nombre' => 'SAN MARTIN DE PORRES', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5-11', 'nombre' => 'VIGUI', 'tipo' => 'corregimiento'],
            ['codigo' => '9-5-12', 'nombre' => 'ZAPOTILLO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-6', 'nombre' => 'MONTIJO', 'tipo' => 'distrito'],
            ['codigo' => '9-6-1', 'nombre' => 'MONTIJO (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-6-2', 'nombre' => 'ARENAS', 'tipo' => 'corregimiento'],
            ['codigo' => '9-6-3', 'nombre' => 'GOBERNADORA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-6-4', 'nombre' => 'LA GARCEANA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-6-5', 'nombre' => 'LEONES', 'tipo' => 'corregimiento'],
            ['codigo' => '9-6-6', 'nombre' => 'CEBACO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-6-7', 'nombre' => 'COSTA HERMOSA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-6-8', 'nombre' => 'UNION DEL NORTE', 'tipo' => 'corregimiento'],
            ['codigo' => '9-6-9', 'nombre' => 'TEBARIO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-6-10', 'nombre' => 'EL PILON', 'tipo' => 'corregimiento'],
            ['codigo' => '9-7', 'nombre' => 'RIO DE JESUS', 'tipo' => 'distrito'],
            ['codigo' => '9-7-1', 'nombre' => 'RIO DE JESUS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-7-2', 'nombre' => 'LAS HUACAS', 'tipo' => 'corregimiento'],
            ['codigo' => '9-7-3', 'nombre' => 'LOS CASTILLOS', 'tipo' => 'corregimiento'],
            ['codigo' => '9-7-4', 'nombre' => 'UTIRA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-7-5', 'nombre' => 'CATORCE DE NOVIEMBRE', 'tipo' => 'corregimiento'],
            ['codigo' => '9-8', 'nombre' => 'SAN FRANCISCO', 'tipo' => 'distrito'],
            ['codigo' => '9-8-1', 'nombre' => 'SAN FRANCISCO (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-8-2', 'nombre' => 'CORRAL FALSO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-8-3', 'nombre' => 'LOS HATILLOS', 'tipo' => 'corregimiento'],
            ['codigo' => '9-8-4', 'nombre' => 'REMANCE', 'tipo' => 'corregimiento'],
            ['codigo' => '9-8-5', 'nombre' => 'SAN JUAN', 'tipo' => 'corregimiento'],
            ['codigo' => '9-8-6', 'nombre' => 'SAN JOSE', 'tipo' => 'corregimiento'],
            ['codigo' => '9-9', 'nombre' => 'SANTA FE', 'tipo' => 'distrito'],
            ['codigo' => '9-9-1', 'nombre' => 'SANTA FE (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-9-2', 'nombre' => 'CALOVEBORA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-9-3', 'nombre' => 'EL ALTO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-9-4', 'nombre' => 'EL CUAY', 'tipo' => 'corregimiento'],
            ['codigo' => '9-9-5', 'nombre' => 'EL PANTANO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-9-6', 'nombre' => 'GATU O GATUCITO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-9-7', 'nombre' => 'RIO LUIS', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10', 'nombre' => 'SANTIAGO', 'tipo' => 'distrito'],
            ['codigo' => '9-10-1', 'nombre' => 'SANTIAGO (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10-2', 'nombre' => 'LA COLORADA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10-3', 'nombre' => 'LA PEÑA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10-4', 'nombre' => 'LA RAYA DE SANTA MARIA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10-5', 'nombre' => 'PONUGA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10-6', 'nombre' => 'SAN PEDRO DEL ESPINO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10-7', 'nombre' => 'CANTO DEL LLANO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10-8', 'nombre' => 'LOS ALGARROBOS', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10-9', 'nombre' => 'CARLOS SANTANA AVILA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10-10', 'nombre' => 'EDWIN FABREGA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10-11', 'nombre' => 'SAN MARTIN DE PORRES', 'tipo' => 'corregimiento'],
            ['codigo' => '9-10-12', 'nombre' => 'URRACA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-11', 'nombre' => 'SONA', 'tipo' => 'distrito'],
            ['codigo' => '9-11-1', 'nombre' => 'SONA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-11-2', 'nombre' => 'BAHIA HONDA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-11-3', 'nombre' => 'CALIDONIA', 'tipo' => 'corregimiento'],
            ['codigo' => '9-11-4', 'nombre' => 'CATIVE', 'tipo' => 'corregimiento'],
            ['codigo' => '9-11-5', 'nombre' => 'EL MARAÑON', 'tipo' => 'corregimiento'],
            ['codigo' => '9-11-6', 'nombre' => 'GUARUMAL', 'tipo' => 'corregimiento'],
            ['codigo' => '9-11-7', 'nombre' => 'LA SOLEDAD', 'tipo' => 'corregimiento'],
            ['codigo' => '9-11-8', 'nombre' => 'QUEBRADA DE ORO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-11-9', 'nombre' => 'RIO GRANDE', 'tipo' => 'corregimiento'],
            ['codigo' => '9-11-10', 'nombre' => 'RODEO VIEJO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-12', 'nombre' => 'MARIATO', 'tipo' => 'distrito'],
            ['codigo' => '9-12-1', 'nombre' => 'LLANO DE CATIVAL O MARIATO (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '9-12-2', 'nombre' => 'ARENAS', 'tipo' => 'corregimiento'],
            ['codigo' => '9-12-3', 'nombre' => 'EL CACAO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-12-4', 'nombre' => 'QUEBRO', 'tipo' => 'corregimiento'],
            ['codigo' => '9-12-5', 'nombre' => 'TEBARIO', 'tipo' => 'corregimiento'],
            ['codigo' => '10', 'nombre' => 'COMARCA KUNA YALA', 'tipo' => 'provincia'],
            ['codigo' => '10-1', 'nombre' => 'COMARCA KUNA YALA', 'tipo' => 'distrito'],
            ['codigo' => '10-1-1', 'nombre' => 'NARGANA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '10-1-2', 'nombre' => 'AILIGANDI', 'tipo' => 'corregimiento'],
            ['codigo' => '10-1-3', 'nombre' => 'PUERTO OBALDIA', 'tipo' => 'corregimiento'],
            ['codigo' => '10-1-4', 'nombre' => 'TUBUALA', 'tipo' => 'corregimiento'],
            ['codigo' => '11', 'nombre' => 'COMARCA EMBERA-WOUNAAN', 'tipo' => 'provincia'],
            ['codigo' => '11-1', 'nombre' => 'CEMACO', 'tipo' => 'distrito'],
            ['codigo' => '11-1-1', 'nombre' => 'CIRILO GUAINORA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '11-1-2', 'nombre' => 'LAJAS BLANCAS', 'tipo' => 'corregimiento'],
            ['codigo' => '11-1-3', 'nombre' => 'MANUEL ORTEGA', 'tipo' => 'corregimiento'],
            ['codigo' => '11-2', 'nombre' => 'SAMBU', 'tipo' => 'distrito'],
            ['codigo' => '11-2-1', 'nombre' => 'RIO SABALO', 'tipo' => 'corregimiento'],
            ['codigo' => '11-2-2', 'nombre' => 'JINGURUDO', 'tipo' => 'corregimiento'],
            ['codigo' => '12', 'nombre' => 'COMARCA NGÄBE-BUGLÉ', 'tipo' => 'provincia'],
            ['codigo' => '12-1', 'nombre' => 'BESIKO', 'tipo' => 'distrito'],
            ['codigo' => '12-1-1', 'nombre' => 'SOLOY (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '12-1-2', 'nombre' => 'BOCA DE BALSA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-1-3', 'nombre' => 'CAMARON ARRIBA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-1-4', 'nombre' => 'CERRO BANCO', 'tipo' => 'corregimiento'],
            ['codigo' => '12-1-5', 'nombre' => 'CERRO DE PATENA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-1-6', 'nombre' => 'EMPLANADA DE CHORCHA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-1-7', 'nombre' => 'NAMNONI', 'tipo' => 'corregimiento'],
            ['codigo' => '12-1-8', 'nombre' => 'NIBA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-2', 'nombre' => 'MIRONO', 'tipo' => 'distrito'],
            ['codigo' => '12-2-1', 'nombre' => 'HATO PILON (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '12-2-2', 'nombre' => 'CASCABEL', 'tipo' => 'corregimiento'],
            ['codigo' => '12-2-3', 'nombre' => 'HATO COROTU', 'tipo' => 'corregimiento'],
            ['codigo' => '12-2-4', 'nombre' => 'HATO CULANTRO', 'tipo' => 'corregimiento'],
            ['codigo' => '12-2-5', 'nombre' => 'HATO JOBO', 'tipo' => 'corregimiento'],
            ['codigo' => '12-2-6', 'nombre' => 'HATO JULI', 'tipo' => 'corregimiento'],
            ['codigo' => '12-2-7', 'nombre' => 'QUEBRADA DE LORO', 'tipo' => 'corregimiento'],
            ['codigo' => '12-2-8', 'nombre' => 'SALTO DUPI', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3', 'nombre' => 'MUNA', 'tipo' => 'distrito'],
            ['codigo' => '12-3-1', 'nombre' => 'CHICHICA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3-2', 'nombre' => 'ALTO CABALLERO', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3-3', 'nombre' => 'BAKAMA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3-4', 'nombre' => 'CERRO CAÑA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3-5', 'nombre' => 'CERRO PUERCO', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3-6', 'nombre' => 'KRUA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3-7', 'nombre' => 'MARACA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3-8', 'nombre' => 'NIBRA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3-9', 'nombre' => 'PEÑA BLANCA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3-10', 'nombre' => 'ROKA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3-11', 'nombre' => 'SITIO PRADO', 'tipo' => 'corregimiento'],
            ['codigo' => '12-3-12', 'nombre' => 'UMANI', 'tipo' => 'corregimiento'],
            ['codigo' => '12-4', 'nombre' => 'NOLE DUIMA', 'tipo' => 'distrito'],
            ['codigo' => '12-4-1', 'nombre' => 'CERRO IGLESIAS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '12-4-2', 'nombre' => 'HATO CHAMI', 'tipo' => 'corregimiento'],
            ['codigo' => '12-4-3', 'nombre' => 'JADEBERI', 'tipo' => 'corregimiento'],
            ['codigo' => '12-4-4', 'nombre' => 'LAJERO', 'tipo' => 'corregimiento'],
            ['codigo' => '12-4-5', 'nombre' => 'SUSAMA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-5', 'nombre' => 'NURUM', 'tipo' => 'distrito'],
            ['codigo' => '12-5-1', 'nombre' => 'BUENOS AIRES (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '12-5-2', 'nombre' => 'AGUA DE SALUD', 'tipo' => 'corregimiento'],
            ['codigo' => '12-5-3', 'nombre' => 'ALTO DE JESUS', 'tipo' => 'corregimiento'],
            ['codigo' => '12-5-4', 'nombre' => 'CERRO PELADO', 'tipo' => 'corregimiento'],
            ['codigo' => '12-5-5', 'nombre' => 'EL BALE', 'tipo' => 'corregimiento'],
            ['codigo' => '12-5-6', 'nombre' => 'EL PAREDON', 'tipo' => 'corregimiento'],
            ['codigo' => '12-5-7', 'nombre' => 'EL PIRO', 'tipo' => 'corregimiento'],
            ['codigo' => '12-5-8', 'nombre' => 'GUAYABITO', 'tipo' => 'corregimiento'],
            ['codigo' => '12-5-9', 'nombre' => 'GUIBALE', 'tipo' => 'corregimiento'],
            ['codigo' => '12-6', 'nombre' => 'KANKINTU', 'tipo' => 'distrito'],
            ['codigo' => '12-6-1', 'nombre' => 'BISIRA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '12-6-2', 'nombre' => 'BURI', 'tipo' => 'corregimiento'],
            ['codigo' => '12-6-3', 'nombre' => 'GUARIVIARA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-6-4', 'nombre' => 'GUORONI', 'tipo' => 'corregimiento'],
            ['codigo' => '12-6-5', 'nombre' => 'KANKINTU', 'tipo' => 'corregimiento'],
            ['codigo' => '12-6-6', 'nombre' => 'MUNUNI', 'tipo' => 'corregimiento'],
            ['codigo' => '12-6-7', 'nombre' => 'PIEDRA ROJA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-6-8', 'nombre' => 'TUWAI', 'tipo' => 'corregimiento'],
            ['codigo' => '12-6-9', 'nombre' => 'MAN CREEK', 'tipo' => 'corregimiento'],
            ['codigo' => '12-7', 'nombre' => 'KUSAPIN', 'tipo' => 'distrito'],
            ['codigo' => '12-7-1', 'nombre' => 'KUSAPIN (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '12-7-2', 'nombre' => 'BAHIA AZUL', 'tipo' => 'corregimiento'],
            ['codigo' => '12-7-3', 'nombre' => 'CALOVEBORA O SANTA CATALINA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-7-4', 'nombre' => 'LOMA YUCA', 'tipo' => 'corregimiento'],
            ['codigo' => '12-7-5', 'nombre' => 'RIO CHIRIQUI', 'tipo' => 'corregimiento'],
            ['codigo' => '12-7-6', 'nombre' => 'TOBOBE', 'tipo' => 'corregimiento'],
            ['codigo' => '12-7-7', 'nombre' => 'VALLE BONITO', 'tipo' => 'corregimiento'],
            ['codigo' => '13', 'nombre' => 'PANAMA OESTE', 'tipo' => 'provincia'],
            ['codigo' => '13-1', 'nombre' => 'ARRAIJAN', 'tipo' => 'distrito'],
            ['codigo' => '13-1-1', 'nombre' => 'ARRAIJAN (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '13-1-2', 'nombre' => 'BURUNGA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-1-3', 'nombre' => 'CERRO SILVESTRE', 'tipo' => 'corregimiento'],
            ['codigo' => '13-1-4', 'nombre' => 'JUAN DEMOSTENES AROSEMENA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-1-5', 'nombre' => 'NUEVO EMPERADOR', 'tipo' => 'corregimiento'],
            ['codigo' => '13-1-6', 'nombre' => 'SANTA CLARA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-1-7', 'nombre' => 'VERACRUZ', 'tipo' => 'corregimiento'],
            ['codigo' => '13-1-8', 'nombre' => 'VISTA ALEGRE', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2', 'nombre' => 'CAPIRA', 'tipo' => 'distrito'],
            ['codigo' => '13-2-1', 'nombre' => 'CAPIRA (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-2', 'nombre' => 'CAIMITO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-3', 'nombre' => 'CAMPANA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-4', 'nombre' => 'CERMEÑO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-5', 'nombre' => 'CIRI DE LOS SOTOS', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-6', 'nombre' => 'CIRI GRANDE', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-7', 'nombre' => 'EL CACAO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-8', 'nombre' => 'LA TRINIDAD', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-9', 'nombre' => 'LAS OLLAS ARRIBA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-10', 'nombre' => 'LIDICE', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-11', 'nombre' => 'VILLA CARMEN', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-12', 'nombre' => 'VILLA ROSARIO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-2-13', 'nombre' => 'SANTA ROSA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-3', 'nombre' => 'CHAME', 'tipo' => 'distrito'],
            ['codigo' => '13-3-1', 'nombre' => 'CHAME (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '13-3-2', 'nombre' => 'BEJUCO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-3-3', 'nombre' => 'BUENOS AIRES', 'tipo' => 'corregimiento'],
            ['codigo' => '13-3-4', 'nombre' => 'CABUYA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-3-5', 'nombre' => 'CHICA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-3-6', 'nombre' => 'EL LIBANO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-3-7', 'nombre' => 'LAS LAJAS', 'tipo' => 'corregimiento'],
            ['codigo' => '13-3-8', 'nombre' => 'NUEVA GORGONA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-3-9', 'nombre' => 'PUNTA CHAME', 'tipo' => 'corregimiento'],
            ['codigo' => '13-3-10', 'nombre' => 'SAJALICES', 'tipo' => 'corregimiento'],
            ['codigo' => '13-3-11', 'nombre' => 'SORA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4', 'nombre' => 'LA CHORRERA', 'tipo' => 'distrito'],
            ['codigo' => '13-4-1', 'nombre' => 'BARRIO BALBOA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-2', 'nombre' => 'BARRIO COLON', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-3', 'nombre' => 'AMADOR', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-4', 'nombre' => 'AROSEMENA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-5', 'nombre' => 'EL ARADO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-6', 'nombre' => 'EL COCO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-7', 'nombre' => 'FEUILLET', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-8', 'nombre' => 'GUADALUPE', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-9', 'nombre' => 'HERRERA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-10', 'nombre' => 'HURTADO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-11', 'nombre' => 'ITURRALDE', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-12', 'nombre' => 'LA REPRESA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-13', 'nombre' => 'LOS DIAZ', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-14', 'nombre' => 'MENDOZA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-15', 'nombre' => 'OBALDIA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-16', 'nombre' => 'PLAYA LEONA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-17', 'nombre' => 'PUERTO CAIMITO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-4-18', 'nombre' => 'SANTA RITA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-5', 'nombre' => 'SAN CARLOS', 'tipo' => 'distrito'],
            ['codigo' => '13-5-1', 'nombre' => 'SAN CARLOS (CABECERA)', 'tipo' => 'corregimiento'],
            ['codigo' => '13-5-2', 'nombre' => 'EL ESPINO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-5-3', 'nombre' => 'EL HIGO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-5-4', 'nombre' => 'GUAYABITO', 'tipo' => 'corregimiento'],
            ['codigo' => '13-5-5', 'nombre' => 'LA ERMITA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-5-6', 'nombre' => 'LA LAGUNA', 'tipo' => 'corregimiento'],
            ['codigo' => '13-5-7', 'nombre' => 'LAS UVAS', 'tipo' => 'corregimiento'],
            ['codigo' => '13-5-8', 'nombre' => 'LOS LLANITOS', 'tipo' => 'corregimiento'],
            ['codigo' => '13-5-9', 'nombre' => 'SAN JOSE', 'tipo' => 'corregimiento']
        ]);
    }

    public function down()
    {
        Schema::dropIfExists('dgi_ubi_codes');
    }
} 